### ISSUE TITLE
Error message payload missing in Error toast

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-UI#17]
There is a slight regression displaying the error toasts. In particular, when an HTTP request fails, you will see the HTTP response code, but the actual error payload is no longer displayed.

for example in the flash node tab:
* Insert a module that is not supported by turing pi
* try to flash image to node
* the corresponding HTTP request returns with 'Request failed with status code 500'
* a toast is show with:

```
Failed to transfer the image to node 4
Request failed with status code 500
```

# expected behavior

the payload of the error response to be present in the toast
something similar to: 

```
Failed to transfer the image to node 4
Compute module's USB interface not found or supported
```

# context
Attached is a screen of the given error response
![err_response_000](https://github.com/user-attachments/assets/2bb0eb53-1ba4-48cc-b38f-67799f98c35a)

**Comment by barrenechea** [comment]
I got it! I'm sorry about it. I don't think I was able to trigger an error during OS uploads. I'll take a look in the afternoon! (Thinking about it, I guess I could replicate it by just releasing a node from its socket and "attempting to flash it" 🤣)

A minor thing is that no matter which language the user has set, the error responses would always be in English (because we'd "pipe it" to the UI). I may propose an improvement for `bmcd` in the future to handle that 😄
